
SIM_TIME = 1000
X_SIZE = 157
Y_SIZE = 157
GRID_SIZE = X_SIZE * Y_SIZE
MAX_DISTANCE = X_SIZE + Y_SIZE

N_PASSENGERS = 1000
DELAY_TOLERATION = 100
TIME_OUT_NO_MATCH = 10

N_TAXI = 75
SHARING_RATE = 0
NODES_LIMIT = 5
N_PUBLIC = round(N_TAXI * SHARING_RATE)
N_PRIVATE = round(N_TAXI * (1 - SHARING_RATE))



DEBUG_ID = 505
DEBUG_COUNT = 0